#!/bin/bash
################################################################################
# @(#) goo(1sh) - Google Quicksearch
export STRING=$(echo "$*"|sed -e 's/ /%20/g')
STRINGHTTP='http://www.google.com/search?q='"$STRING"
################################################################################
if inpath.sh xdg-open
then
   # red hat linux
   xdg-open "$STRINGHTTP"
else
   set -x
   browser "$iSTRINGHTTP"
fi
################################################################################
exit
################################################################################
